pub mod lex;
pub use lex::Lexer;

pub mod parser;
pub use parser::Parser;

pub mod evaluation;
pub use evaluation::Interpreter;

use miette::{LabeledSpan, MietteDiagnostic, Report};

/// Holds a reference to the source code with position information
///
/// Generated by the lexer, then passed to higher levels to maintain error reporting
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct SourceLoc<'de> {
    pub source: &'de str,
    pub offset: usize,
    pub len: usize,
}

impl From<SourceLoc<'_>> for miette::SourceSpan {
    fn from(value: SourceLoc<'_>) -> Self {
        miette::SourceSpan::new(value.offset.into(), value.len)
    }
}

impl From<&SourceLoc<'_>> for miette::SourceSpan {
    fn from(value: &SourceLoc<'_>) -> Self {
        miette::SourceSpan::new(value.offset.into(), value.len)
    }
}

/// Add source information from a [SourceLoc] to a [MietteDiagnostic]
pub trait WithSourceLoc {
    type Wrapped;
    fn with_source_loc(self, loc: &SourceLoc) -> Self::Wrapped;
}

impl WithSourceLoc for MietteDiagnostic {
    type Wrapped = Report;

    fn with_source_loc(self, loc: &SourceLoc) -> Report {
        Report::from(self.with_label(LabeledSpan::new(None, loc.offset, loc.len)))
            .with_source_code(loc.source.to_string())
    }
}

impl<T, E: WithSourceLoc> WithSourceLoc for Result<T, E> {
    type Wrapped = Result<T, E::Wrapped>;

    fn with_source_loc(self, loc: &SourceLoc) -> Self::Wrapped {
        self.map_err(|err| err.with_source_loc(loc))
    }
}
